version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'watchmetoo_db'
      POSTGRES_PASSWORD: 'watchmetoo_db'
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
